name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW (g++ compiler)
      shell: powershell
      run: |
        choco install mingw

    - name: Download freeglut
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://downloads.sourceforge.net/project/freeglut/freeglut/3.2.1/freeglut-3.2.1-bin.zip" -OutFile freeglut.zip
        Expand-Archive -Path freeglut.zip -DestinationPath freeglut

    - name: Build with Make
      shell: cmd
      run: make
