name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW (g++ compiler)
      shell: powershell
      run: |
        choco install mingw
        refreshenv

    - name: Install freeglut via Chocolatey
      shell: powershell
      run: choco install freeglut

    - name: Build with Make
      shell: cmd
      run: make
