name: Build C++ OpenGL on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install freeglut (via Chocolatey)
      run: choco install freeglut

    - name: Compile the project
      shell: cmd
      run: |
        dir
        g++ main.cpp imageloader.cpp -o app.exe -IC:\tools\freeglut\include -LC:\tools\freeglut\lib -lfreeglut -lopengl32
