name: Build with MSYS2 on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2 and dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-freeglut
        msystem: MINGW64

    - name: Build project
      shell: msys2 {0}
      working-directory: ${{ github.workspace }}
      run: |
        make

