name: C++ OpenGL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OpenGL and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    - name: Confirm g++ is installed
      run: which g++

    - name: Compile project
      run: |
        mkdir -p build
        g++ -o build/app main.cpp -lGL -lGLU -lglut
