name: Build C++ OpenGL (main.cpp only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenGL libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev

    - name: Compile main.cpp
      run: |
        mkdir -p build
        g++ -o build/main main.cpp -lGL -lGLU -lglut
