name: Build with MSYS2 on Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install MSYS2
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20230501.exe" -OutFile msys2.exe
        Start-Process msys2.exe -ArgumentList "/S" -Wait

    - name: Update MSYS2 and install packages
      shell: bash
      run: |
        # Update package database and base packages
        pacman -Syuu --noconfirm

        # Sometimes requires 2 runs, so run again if needed
        pacman -Syuu --noconfirm || true

        # Install gcc, freeglut, make
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freeglut mingw-w64-x86_64-make

    - name: Build project
      shell: bash
      run: |
        export PATH="/mingw64/bin:$PATH"
        make
