name: Build with MSYS2 on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-freeglut
          mingw-w64-x86_64-make

    - name: Build project
      shell: bash
      working-directory: src  # or your source folder name
      run: |
        export PATH="/mingw64/bin:$PATH"
        make

